Chart/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from views import Index, Login

admin.autodiscover()


urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^$', Index.as_view(), name='index'),
                       url(r'^login/$', Login.as_view(), name='login'),
                       url(r'^sensors/', include('sensors.urls', namespace='sensors')),
                       url(r'^messages/', include('messages.urls', namespace='messages')),



        )

messages/urls.py
from django.conf.urls import patterns, url
from views import Message


urlpatterns = patterns('',
                       url(r'^(?P<location>\w+)/$', Message.as_view(), name='message'),
                       )

sensors/urls.py
from django.conf.urls import patterns, url
from views import Graphic, TrendEdit, Explosion, online_update


urlpatterns = patterns('',
                       url(r'^graphic/(?P<location>\w+)/(?P<trend>[0-9]+)/$', Graphic.as_view(), name='graphic'),
                       url(r'^edit/(?P<location>\w+)/(?P<trend>[0-9]+)/$', TrendEdit.as_view(), name='edit'),
                       url(r'^update/(?P<location>\w+)/(?P<trend>[0-9]+)/$', online_update),
                       url(r'^explosion/(?P<location>\w+)/$', Explosion.as_view(), name='explosion'),
                       )

messages/models.py
from django.db import models
from sensors.models import PLC, Location


class MessageType(models.Model):
    id = models.AutoField(primary_key=True, db_column='Id')
    text = models.CharField(max_length=50, db_column='Type')

    class Meta:
        db_table = 'MessageType'


class Message(models.Model):
    id = models.AutoField(primary_key=True, db_column='Id')
    text = models.CharField(max_length=255, db_column='Text')
    address = models.CharField(max_length=50, db_column='Address')
    plc = models.ForeignKey(PLC, db_column='PLCID')
    type = models.ForeignKey(MessageType, db_column='TypeId')
    location = models.ForeignKey(Location, db_column='LocationId')

    class Meta:
        db_table = 'Message'


class MessageList(models.Model):
    id = models.AutoField(primary_key=True, db_column='Id')
    message = models.ForeignKey(Message, db_column='MessageID')
    state = models.BooleanField(db_column='State')
    value = models.FloatField(db_column='Value', blank=True, null=True)
    time_stamp = models.DateTimeField(db_column='TimeStamp')

    class Meta:
        db_table = 'MessageList'

messages/views.py
from django.views.generic import ListView
from datetime import datetime, timedelta
from models import MessageList, MessageType


class Message(ListView):
    template_name = 'message.html'

    def get_queryset(self):
        try:
            self.date_to = datetime.strptime(self.request.GET['to'], '%Y-%m-%dT%H:%M')
            self.date_from = datetime.strptime(self.request.GET['from'], '%Y-%m-%dT%H:%M')
        except KeyError:
            self.date_to = datetime.now()
            self.date_from = self.date_to - timedelta(hours=2)
        self.message_type = self.request.GET.get('type', 'All')
        self.message_state = self.request.GET.get('state', 'All')
        qs = MessageList.objects.filter(message__location__name=self.kwargs['location'])\
                                .filter(time_stamp__range=(self.date_from, self.date_to))\
                                .order_by('-time_stamp')
        if self.message_type != 'All':
            qs = qs.filter(message__type__text=self.message_type)
        if self.message_state != 'All':
            if self.message_state == 'Active':
                state = True
            else:
                state = False
            qs = qs.filter(state=state)
        return qs

    def get_context_data(self, **kwargs):
        context = super(Message, self).get_context_data(**kwargs)
        context['date_to'] = self.date_to.strftime('%Y-%m-%dT%H:%M')
        context['date_from'] = self.date_from.strftime('%Y-%m-%dT%H:%M')
        context['types'] = MessageType.objects.all()
        context['cur_type'] = self.message_type
        context['states'] = ('Active', 'Non Active')
        context['cur_state'] = self.message_state
        context['location'] = self.kwargs['location']
        return context

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block tittle %}{% endblock %}</title>

    {% block static %}
    {% load static %}
        <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
</head>
<body>
    <nav class="navbar col-md-10 col-md-offset-1" role="navigation">
        <div>
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index' %}"></a>
            </div>
            <div class="collapse navbar-collapse" id="top-navbar-1">
                <ul class="nav navbar-nav">
                    <li class="{% if location == 'Index' %}active{% endif %}">
                        <a href="{% url 'index' %}"><i class="fa fa-home"></i><br>Главная</a>
                    </li>
                    <li class="dropdown {% if location == 'Krones' %}active{% endif %}">
                        <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">
                            <i class="fa fa-hourglass-half"></i><br>Пастеризатор<br>Krones<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-left" role="menu">
                            <li><a href="{% url 'sensors:graphic' 'Krones' 1 %}">Графики</a></li>
                            <li><a href="{% url 'messages:message' 'Krones' %}">Сообщения</a></li>
                        </ul>
                    </li>
                    <li class="dropdown {% if location == 'KEG' %}active{% endif %}">
                        <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">
                            <i class="fa fa-hourglass-half"></i><br>Пастеризатор<br>KEG<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-left" role="menu">
                            <li><a href="{% url 'sensors:graphic' 'KEG' 1 %}">Графики</a></li>
                            <li><a href="{% url 'messages:message' 'KEG' %}">Сообщения</a></li>
                        </ul>
                    </li>
                    <li class="dropdown {% if location == 'PET' %}active{% endif %}">
                        <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">
                            <i class="fa fa-hourglass-half"></i><br>Пастеризатор<br>PET<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-left" role="menu">
                            <li><a href="{% url 'sensors:graphic' 'PET' 1 %}">Графики</a></li>
                            <li><a href="{% url 'messages:message' 'PET' %}">Сообщения</a></li>
                        </ul>
                    </li>
                    <li class="dropdown {% if location == 'Parameters' or location == 'Streamers' %}active{% endif %}">
                        <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">
                            <i class="fa fa-hourglass-half"></i><br>Наливатели<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-left" role="menu">
                            <li><a href="{% url 'sensors:graphic' 'Parameters' 1 %}">Графики</a></li>
                            <li><a href="{% url 'sensors:explosion' 'Streamers' %}">Взрывы</a></li>
                        </ul>
                    </li>
                    <li class="{% if location == 'Login' %}active{% endif %}">
                        <a href="{% url 'login' %}"><i class="fa fa-user"></i><br>
                            {% if user.is_active %} {{ user }} {% else %} Войти {% endif %}
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="navbar-brand" id="elaks-logo" href="#"></a></li>
                </ul>
            </div>

        </div>
    </nav>

    <div id="line" class="col-md-12"></div>
    <div class="col-md-10 col-md-offset-1">
        {% block body %}
        {% endblock %}
    </div>

    {% block javaScriptInclude %}
        <script src="{% static 'js/jquery-2.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/bootstrap-hover-dropdown.min.js' %}"></script>
    {% endblock %}
</body>
</html>

templates/explosion.html
{% extends 'base.html' %}
{% block tittle %}
Explosions
{% endblock %}
{% block body %}
<form class="form-inline">
    <div class="form-group">
        <label for="from">Начало</label>
        <input type="datetime-local" name="from" value="{{ date_from }}">
    </div>
    <div class="form-group">
        <label for="to">Конец</label>
        <input type="datetime-local" name="to" value="{{ date_to }}">
    </div>
    <div class="form-group">
        <span>Наливатель</span>
        <select class="form-control" name="streamer">
            <option>All</option>
            {% for streamer in streamers %}
                <option {% if cur_streamer == streamer.id %}selected="selected"{% endif %} value="{{ streamer.id }}">
                    {{ streamer.description }}
                </option>
            {% endfor %}
        </select>
    </div>
    <button type="submit">Показать</button>
</form>

<table class="table table-condensed">
{% if cur_streamer == 'All' %}
    <tr>
        <td>Наливатель</td>
        <td>Количество взрывов</td>
    </tr>
    {% for object in object_list %}
        <tr>
            <td>{{ object.name }}</td>
            <td>{{ object.value }}</td>
        </tr>
    {% endfor %}
{% else %}
    <tr>
        <td>Дата</td>
        <td>Номер взрыва</td>
        <td>Скорость моноблока, бут/час</td>
        <td>Давление пива, бар</td>
        <td>Уровень пива, мм</td>
        <td>Величина вакуума, бар</td>
    </tr>
    {% for object in object_list %}
        <tr>
            <td>{{ object.explosion_date|date:"Y-m-d, H:i:s" }}</td>
            <td>{{ object.explosion_number }}</td>
            <td>{{ object.MonoActualSpeed }}</td>
            <td>{{ object.Pbeer_circul_Buf }}</td>
            <td>{{ object.Lbeer_circul_Buf }}</td>
            <td>{{ object.Vacum }}</td>
        </tr>
    {% endfor %}

{% endif %}
</table>
{% endblock %}

templates/graphic.html
{% extends 'base.html' %}
{% block title %}{{ location }}{% endblock %}
{% block body %}
    <form class="form-inline">
        <div class="form-group">
            <select id="chart_type">
                <option value="online">Онлайн</option>
                <option value="offline">За указанный период</option>
            </select>
        </div>
        <div class="form-group">
            <label for="from">Начало</label>
            <input type="datetime-local" name="from" id="from" required disabled><br>
        </div>
        <div class="form-group">
            <label for="to">Конец</label>
            <input type="datetime-local" name="to" id="to" required disabled>
        </div>
        <div class="form-group">
             <input type="submit" value="Показать" id="chart_show_btn" disabled>
        </div>
    </form>

    <div id="chart-container"></div>

    <ul class="nav nav-tabs">
    {% for q in trend_qs %}
        <li role="presentation" {% ifequal cur_trend_num q.number %}class="active"{% endifequal %}>
            <a href="{% url 'sensors:graphic' location q.number %}">{{ q.number }}</a>
        </li>
    {% endfor %}
    </ul>

<table class="table table-bordered">
  <tr>
      <td style="width: 4em">#</td>
      <td style="width: 15em">Имя тренда</td>
      <td>Описание</td>
      <td style="width: 5em">Единицы измерения</td>
      <td style="width: 5em">Цвет</td>
  </tr>
  {% for sensor in sensors %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ sensor.name }}</td>
        <td>{{ sensor.description }}</td>
        <td>{{ sensor.egu }}</td>
        <td><input type="color" id="{{ forloop.counter }}" name="color{{ sensor.number }}" class="color" value="{{ sensor.color }}"></td>
    </tr>
    {% endfor %}
</table>

{% if user.is_active %}
    <a href="{% url 'sensors:edit' location trend %}" class="btn btn-default">Изменить</a>
{% endif %}
{% endblock %}

{% block javaScriptInclude %}
{% load static %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/highcharts.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/exporting.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/chart.js' %}"></script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}Index{% endblock %}

{% block body %}


{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block body %}
<form class="form-inline"  method="post">
    {% csrf_token %}
    <div class="form-group">
         <label for="Username">Имя пользователя:</label>
         <input type="text" name="username">
    </div>
    <div class="form-group">
         <label for="Password">Пароль:</label>
        <input type="password" name="password">
    </div>
    <div class="form-group">
        <input type="submit" value="Войти">
    </div>

</form>
    {{ message }}
{% endblock %}

templates/message.html
{% extends 'base.html' %}
{% block title %}Message{% endblock %}
{% block message_active %}active{% endblock %}
{% block body %}
<form class="form-inline">
    <div class="form-group">
        <label for="from">Начало</label>
        <input type="datetime-local" name="from" value="{{ date_from }}">
    </div>
    <div class="form-group">
        <label for="to">Конец</label>
        <input type="datetime-local" name="to" value="{{ date_to }}">
    </div>
    <div class="form-group">
        <span>Тип</span>
        <select class="form-control" name="type">
            <option>All</option>
            {% for type in types %}
                <option {% ifequal cur_type type.text %}selected="selected"{% endifequal %}>{{ type.text }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <span>Состояние</span>
        <select class="form-control" name="state">
            <option>All</option>
            {% for state in states %}
                <option {% ifequal cur_state state %}selected="selected"{% endifequal %}>{{ state }}</option>
            {% endfor %}
        </select>
    </div>
    <button type="submit">Показать</button>
</form>

<table class="table table-condensed">
  <tr>
      <td>#</td>
      <td>Время</td>
      <td>Описание</td>
      <td>Тип</td>
      <td>Состояние</td>
  </tr>
  {% for object in object_list %}
  <tr class="{{ object.message.type.text }} {{ object.state }}">
    <td>{{ forloop.counter }}</td>
    <td>{{ object.time_stamp|date:"Y-m-d, H:i:s" }}</td>
    <td>{{ object.message.text }}</td>
    <td>{{ object.message.type.text }}</td>
    <td>{{ object.state }}</td>
  </tr>
  {% endfor %}
</table>

{% endblock %}

templates/pasteurizer.html
{% extends 'base.html' %}
{% block title %}Pasteurizer {{ pasteurizer }}{% endblock %}
{% load static %}
{% block static %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/highcharts.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/exporting.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/get-highchart.js' %}"></script>
{% endblock %}

{% block body %}
    <form class="form-inline">
        <div class="form-group">
            <select id="chart_type">
                <option value="online">Онлайн</option>
                <option value="offline">За указанный период</option>
            </select>
        </div>
        <div class="form-group">
            <label for="from">Начало</label>
            <input type="datetime-local" name="from" id="from" required disabled><br>
        </div>
        <div class="form-group">
            <label for="to">Конец</label>
            <input type="datetime-local" name="to" id="to" required disabled>
        </div>
        <div class="form-group">
             <input type="submit" value="Показать" id="chart_show_btn" disabled>
        </div>
    </form>

    <div id="chart-container"></div>

<ul class="nav nav-tabs">
    {% for q in trend_qs %}
        <li role="presentation" {% ifequal trend q.number %}class="active"{% endifequal %}><a href="{% url 'pasteurizer' pasteurizer q.number %}">{{ q.number }}</a></li>
    {% endfor %}
</ul>

<table class="table table-bordered">
  <tr>
      <td style="width: 4em">#</td>
      <td style="width: 15em">Имя тренда</td>
      <td>Описание</td>
      <td style="width: 5em">Цвет</td>
  </tr>
  {% for trend in trends %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ trend.name }}</td>
        <td>{{ trend.description }}</td>
        <td><input type="color" id="{{ forloop.counter }}" name="color{{ trend.number }}" class="color" value="{{ trend.color }}"></td>
    </tr>
    {% endfor %}
</table>

{% if user.is_active %}
    <a href="{% url 'trend_edit' pasteurizer trend %}" class="btn btn-default">Изменить</a>
{% endif %}
{% endblock %}

templates/trend_edit.html
{% extends 'base.html' %}
{% load static %}
{% block static %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/trend.css' %}">
{% endblock %}
{% block body %}
    <p>Location: {{ object.location }}</p>
    <p>Number: {{ object.number }}</p>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить" />
    </form>
{% endblock %}